config/routes.rb
Rails.application.routes.draw do
  resources :components, only: [:index]

  devise_for :users

  root to: 'pages#home'

  resources :components

  resources :rooms, only: [:index, :show]

  namespace :host do
    root to: 'pages#home'

    resources :housing_requests, only: [:index] do
      member do
        patch :decline
        patch :accept
      end
    end
    resources :rooms, only: [:new, :create]

    resource :offered_equipments, only: [:edit, :update]
    resource :night_proposal, only: [:edit, :update]
  end

  namespace :seeker do
    resources :housing_requests, only: [:index, :show]
    resources :rooms, only: [] do
      resources :housing_requests, only: [:create]
    end

    resource :offered_services, only: [:edit, :update]
    resource :search_infos, only: [:edit, :update]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="top-nav navbar">
    <%# BACK BTN %>
    <%= link_to url_for(:back) do %>
    <div class="button-back"><i class="fas fa-chevron-left"></i></div>
    <% end %>
    
    <%# LOGO %>
    <%= link_to root_path, class: "navbar-logo" do %>
      <%= image_tag('service-icons/main_logo.svg') %>
    <% end %>

    <%# BTN MENU %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <div class="navbar-icon"><i class="fas fa-bars"></i></div>
    </button>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Recherche", edit_seeker_offered_services_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Mes demandes", seeker_housing_requests_path, class: "nav-link" %>
        </li >
        <li class="nav-item">
          <%= link_to "Me déconnecter", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>