config/routes.rb
Rails.application.routes.draw do
  resources :components, only: [:index]

  devise_for :users

  root to: 'pages#home'

  resources :components

  resources :rooms, only: [:index, :show]

  namespace :host do
    root to: 'pages#home'

    resources :housing_requests, only: [:index] do
      member do
        patch :decline
        patch :accept
      end
    end
    resources :rooms, only: [:new, :create]

    resource :offered_equipments, only: [:edit, :update]
    resource :night_proposal, only: [:edit, :update]
  end

  namespace :seeker do
    resources :housing_requests, only: [:index, :show]
    resources :rooms, only: [] do
      resources :housing_requests, only: [:create]
    end

    resource :offered_services, only: [:edit, :update]
    resource :search_infos, only: [:edit, :update]
  end
end

app/models/housing_request.rb
class HousingRequest < ApplicationRecord
  Client = Twilio::REST::Client.new(ENV['TWILIO_ID'], ENV['TWILIO_TOKEN'])
  MAX_NIGHTS_COUNT = 3
  HOUR_BEFORE_POSTPONING_REQUESTS_TO_NEXT_DAY = 23

  belongs_to :room
  belongs_to :seeker, class_name: "User"


  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true

  after_create :send_message

  def pending!
    self.status = :pending
  end


  private

  def send_message
    Client.messages.create(
      from: '+16108970968',
      to: room.host.phone_number || "+33661634782",
      body: "Bonjour, vous avez une d'hébergement de la part de #{seeker&.name}! Vous pouvez vous connectez sur www.dodocho.top afin de lui répondre."
    )
  end
end

app/controllers/host/housing_requests_controller.rb
class Host::HousingRequestsController < ApplicationController
  Client = Twilio::REST::Client.new(ENV['TWILIO_ID'], ENV['TWILIO_TOKEN'])

  require 'twilio-ruby'


  def index
    @requests = current_user.housing_requests.includes(:room).order(created_at: :desc)
  end

  def accept
    @housing_request = HousingRequest.find(params[:id])
    @housing_request.status = "accepted"
    @housing_request.save

    Client.messages.create(
      from: '+16108970968',
      to: @housing_request.seeker.phone_number,
      body: "Votre demande d'hébergement a été acceptée. \
             Vous pouvez vous connecter sur www.dodocho.top pour voir les coordonnées de votre hôte."
    )
    redirect_to host_housing_requests_path
  end


#     TwilioClient.messages.create(
#                   body: ".. accepted your request. His/her number is",
#                   # {current_user.name}
#                   # {current_user.phone_number}. It's your turn now!"
#                   from: '+12312448223',
#                   # to: "#{contact_request.seeker.phone_number}"
#                   to: "+33661634782")

  def decline
    @housing_request = HousingRequest.find(params[:id])
    @housing_request.status = "declined"
    @housing_request.save

    Client.messages.create(
      from: '+16108970968',
      to: @housing_request.seeker.phone_number,
      body: "Désolé, votre demande d'hébergement à été refusée."
    )
    redirect_to host_housing_requests_path
  end

    # TwilioClient.messages
    #             .create(
    #               body: " declined your request... :(",
    #               #{current_user.name}
    #               from: '+12312448223',
    #               # to: "#{contact_request.explorer.phone_number}"
    #               to: '+33661634782'
    #               )

  # def show
  #   @housing_request = HousingRequest.find(params[:id])
  # end

end

app/controllers/host/night_proposal_controller.rb
class Host::NightProposalsController < ApplicationController
def edit

end

def update

end
end

app/controllers/host/night_proposals_controller.rb
class Host::NightProposalsController < ApplicationController
  def edit
  end

  def update
    
    
  end
end

app/controllers/host/offered_equipments_controller.rb
class Host::OfferedEquipmentsController < ApplicationController
  def edit
    # @room = Roomd.find{params[:]}
    @user = current_user
  end

  def update
  end
end

app/controllers/host/rooms_controller.rb
class Host::RoomsController < ApplicationController
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.host = current_user
    if @room.save
      # renvoyer l'utilisateur vers le formulaire d'edit de la room pour ajouter les équipements
      redirect_to edit_host_offered_equipments_path
    else
      render 'new'
    end
  end

  private

  def room_params
    params.require(:room).permit(:id, :summary, :title, :body, :photos)
  end
end

app/controllers/seeker/housing_requests_controller.rb
class Seeker::HousingRequestsController < ApplicationController
  def index
    @requests = current_user.requests.includes(:room).order(created_at: :desc)
  end

  def create
    current_time = Time.now
    nights_count_requested = session[:nights_count_chosen]

    limit_time = Time.now.change(hour: HousingRequest::HOUR_BEFORE_POSTPONING_REQUESTS_TO_NEXT_DAY, min: 0)
    current_day_midnight = Time.now.tomorrow.beginning_of_day

    if current_time <= limit_time
      start_date = current_time.beginning_of_day + 19.hours
    elsif limit_time < current_time && current_time < current_day_midnight
      start_date = current_time.beginning_of_day + 1.day + 19.hours
    else
      start_date = current_time.beginning_of_day + 19.hours
    end

    end_date = (start_date + nights_count_requested.to_i.day).beginning_of_day + 12.hours

    @request = HousingRequest.new(start_date: start_date, end_date: end_date)
    @room = Room.find(params[:room_id])

    @request.room = @room
    @request.seeker = current_user
    @request.pending!

    if @request.save
      redirect_to seeker_housing_requests_path
    else
      render 'rooms/show'
    end
  end

  def show
    @room_id_of_request = HousingRequest.find(params[:id]).room_id
    @room = Room.find(@room_id_of_request)
    @can_see_details = current_user.requests
                                   .where(room: @room, status: "accepted")
                                   .where("housing_requests.end_date >= ?", Date.today)
                                   .exists?
  end
end

app/views/host/housing_requests/_housing_requests.html.erb
<div class="card-index shadow mt-3">
  <div class="card-index-image-wrapper" style="background-image: linear-gradient(rgba(0,0,0,.3),rgba(0,0,0,.3)), url(<%= cl_image_path room.photos.first.key %>); background-position: center; background-size: cover">
    <h2><%= room.title %></h2>
  </div>
  <div class="card-footer-description-wrapper p-3 d-flex justify-content-between align-items-center">
    <div class="d-flex align-items-center justify-content-between flex-row flex-grow-1">
      <div class="d-flex flex-grow-1 align-items-center justify-content-between">
        <div>
          <% if room.has_tv %>
            <i class="fas fa-1x fa-tv mr-2"></i>
          <% end %>
          <% if room.has_internet %>
            <i class="fas fa-1x fa-wifi mr-2"></i>
          <% end %>
          <% if room.has_books %>
            <i class="fas fa-1x fa-book mr-2"></i>
          <% end %>
          <% if room.has_personal_bathroom %>
            <i class="fas fa-1x fa-sink mr-2"></i>
          <% end %>
        </div>
        <% if housing_request.status == "pending" %>
          <div class="d-flex">
            <div class="button-checked mr-3">
              <%= link_to accept_host_housing_request_path(housing_request), method: :patch do %>
                <i class="fas fa-check"></i>
              <% end %>
            </div>
            <div class="button-refuse">
              <%= link_to decline_host_housing_request_path(housing_request), method: :patch do %>
                <i class="fas fa-times"></i>
              <% end %>
            </div>
          </div>
        <% else %>
          <% if housing_request.status == "accepted" %>
            <p class="mr-2 mb-0">Acceptée</p>
            <div class="button-checked">
              <i class="fas fa-check"></i>
            </div>
          <% elsif housing_request.status == "declined" %>
            <p class="mr-2 mb-0">Refusée</p>
            <div class="button-refuse">
              <i class="fas fa-times"></i>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/host/housing_requests/index.html.erb
<div class="container housing-request my-5">
  <div class="row px-3 index-housing-request">
    <h4 style="font-weight: bolder;">Mes demandes</h4>
    <%  @requests.each do |housing_request| %>
      <%= render "host/housing_requests/housing_requests", room: housing_request.room, housing_request: housing_request %>
    <% end %>
    <%= link_to "Ajouter une nouvelle chambre", new_host_room_path, class: "btn btn-gradient btn-block btn-lg mt-5" %>
  </div>
</div>