config/routes.rb
Rails.application.routes.draw do
  resources :components, only: [:index]

  devise_for :users

  root to: 'pages#home'

  resources :components

  resources :rooms, only: [:index, :show]

  namespace :host do
    root to: 'pages#home'

    resources :housing_requests, only: [:index] do
      member do
        patch :decline
        patch :accept
      end
    end
    resources :rooms, only: [:new, :create]

    resource :offered_equipments, only: [:edit, :update]
    resource :night_proposal, only: [:edit, :update]
  end

  namespace :seeker do
    resources :housing_requests, only: [:index, :show]
    resources :rooms, only: [] do
      resources :housing_requests, only: [:create]
    end

    resource :offered_services, only: [:edit, :update]
    resource :search_infos, only: [:edit, :update]
  end
end

app/models/room.rb
class Room < ApplicationRecord
  HOUSING_TYPES = ["dormitory", "personal room", "shared room"]

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many_attached :photos

  belongs_to :host, class_name: "User"
  has_many :housing_requests

  validates :summary, presence: true
  # validates :address, presence: true
  # validates :housing_type, presence: true, inclusion: { in: HOUSING_TYPES }

  def distance_from(coordinates)
    Geocoder::Calculations.distance_between([latitude, longitude], coordinates).floor(1)
  end
end

app/controllers/host/rooms_controller.rb
class Host::RoomsController < ApplicationController
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.host = current_user
    if @room.save
      # renvoyer l'utilisateur vers le formulaire d'edit de la room pour ajouter les équipements
      redirect_to edit_host_offered_equipments_path
    else
      render 'new'
    end
  end

  private

  def room_params
    params.require(:room).permit(:id, :summary, :title, :body, :photos)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    # ! Ici nous avons accès à params[:address], qui nous est fourni par l'utilisateur sur l'écran précédent
    # search_infos/edit
    @rooms = Room.near(params[:address], 10)
    @address_coordinates = Geocoder.coordinates(params[:address])
  end

  def show
    @room = Room.find(params[:id])
    @rooms = Room.near(params[:address], 10)
    @address_coordinates = [params[:lat], params[:long]]
  end
end

app/views/rooms/_room.html.erb
<div class="card-index shadow mt-3">
  <div class="card-index-image-wrapper" style="background-image: linear-gradient(rgba(0,0,0,.4),rgba(0,0,0,.4)), url(<%= cl_image_path room.photos.first.key %>); background-position: center; background-size: cover">
    <h2><%= room.title %></h2>
  </div>
  <div class="card-footer-description-wrapper p-3 d-flex justify-content-between align-items-center">
    <div class="d-flex flex-row flex-grow-1">
      <div>
        <% if room.has_tv %>
          <i class="fas fa-1x fa-tv mr-2"></i>
        <% end %>
        <% if room.has_internet %>
          <i class="fas fa-1x fa-wifi mr-2"></i>
        <% end %>
        <% if room.has_books %>
          <i class="fas fa-1x fa-book mr-2"></i>
        <% end %>
        <% if room.has_personal_bathroom %>
          <i class="fas fa-1x fa-sink mr-2"></i>
        <% end %>
      </div>
      <div class="text-right flex-grow-1 justify-content-end">
        <i class="fas fa-1x fa-map-marker-alt mr-2"></i>
        <%= "#{Geocoder::Calculations.distance_between([room.latitude, room.longitude], @address_coordinates).floor(1)} Km" %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="container global-container-wrapper mt-3">
  <h1 style="font-size: 2em;">Chambres disponibles</h1>
  <%#= session[:nights_count_chosen] %>
</div>

<div class="container">
  <div class="row px-3 index-cards">
  <% @rooms.each do |room| %>
    <%= link_to room_path(room, lat: @address_coordinates.first, long: @address_coordinates.last), class:"text-decoration-none text-dark d-inline-block w-100" do %>
    <%= render "room", room: room %>
    <% end %>
  <% end %>
  <%= link_to 'Modifier mes choix', edit_seeker_offered_services_path, class: "btn btn-gradient btn-block btn-lg mb-3 d-inline-block mt-3" %>
</div>

app/views/rooms/show.html.erb
<div class="container show-room h-100">
  <div class="d-flex flex-column h-100 py-3 mb-5 flex-grow-1">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
        <div class="carousel-inner rounded">
          <div class="carousel-item active">
            <%= cl_image_tag @room.photos.first.key, height: 250, class: "cover d-block w-100" %>
          </div>
          <div class="carousel-item">
            <%= cl_image_tag @room.photos.second.key, height: 250, class: "cover d-block w-100" %>
          </div>
          <div class="carousel-item">
            <%= cl_image_tag @room.photos.last.key, height: 250, class: "cover d-block w-100" %>
          </div>
        </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Précédent</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Suivant</span>
      </a>
    </div>

    <div class="mt-3 py-3 container card-background rounded flex-column d-flex flex-grow-1">
      <div class="text-warning d-flex align-self-end font-weight-bold 1.8rem mb-3">
        <i class="fas fa-2x fa-map-marker-alt mr-3"></i>
        <%= "#{@room.distance_from(@address_coordinates)} Km" %>
      </div>

      <div class="card-description-wrapper flex-grow-1">
        <h4><%= @room.title %></h4>
        <p><%= @room.summary %></p>
      </div>

      <div class="card-footer-description-wrapper d-flex justify-content-around px-5 mx-auto py-3">
        <% if @room.has_tv %>
          <i class="fas fa-1x fa-tv mr-2"></i>
        <% end %>
        <% if @room.has_internet %>
          <i class="fas fa-1x fa-wifi mr-2"></i>
        <% end %>
        <% if @room.has_books %>
          <i class="fas fa-1x fa-book mr-2"></i>
        <% end %>
        <% if @room.has_personal_bathroom %>
          <i class="fas fa-1x fa-sink mr-2"></i>
        <% end %>
      </div>

      <%= link_to "Effectuer la demande", seeker_room_housing_requests_path(@room), method: :post, class: "btn btn-gradient btn-block btn-lg mt-5" %>
    </div>
  </div>
</div>