config/routes.rb
Rails.application.routes.draw do
  resources :components, only: [:index]

  devise_for :users

  root to: 'pages#home'

  resources :components

  resources :rooms, only: [:index, :show]

  namespace :host do
    root to: 'pages#home'

    resources :housing_requests, only: [:index] do
      member do
        patch :decline
        patch :accept
      end
    end
    resources :rooms, only: [:new, :create]

    resource :offered_equipments, only: [:edit, :update]
    resource :night_proposal, only: [:edit, :update]
  end

  namespace :seeker do
    resources :housing_requests, only: [:index, :show]
    resources :rooms, only: [] do
      resources :housing_requests, only: [:create]
    end

    resource :offered_services, only: [:edit, :update]
    resource :search_infos, only: [:edit, :update]
  end
end

app/models/room.rb
class Room < ApplicationRecord
  HOUSING_TYPES = ["dormitory", "personal room", "shared room"]

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many_attached :photos

  belongs_to :host, class_name: "User"
  has_many :housing_requests

  validates :summary, presence: true
  # validates :address, presence: true
  # validates :housing_type, presence: true, inclusion: { in: HOUSING_TYPES }

  def distance_from(coordinates)
    Geocoder::Calculations.distance_between([latitude, longitude], coordinates).floor(1)
  end
end

app/controllers/host/housing_requests_controller.rb
class Host::HousingRequestsController < ApplicationController
  Client = Twilio::REST::Client.new(ENV['TWILIO_ID'], ENV['TWILIO_TOKEN'])

  require 'twilio-ruby'


  def index
    @requests = current_user.housing_requests.includes(:room).order(created_at: :desc)
  end

  def accept
    @housing_request = HousingRequest.find(params[:id])
    @housing_request.status = "accepted"
    @housing_request.save

    Client.messages.create(
      from: '+16108970968',
      to: @housing_request.seeker.phone_number,
      body: "Votre demande d'hébergement a été acceptée. \
             Vous pouvez vous connecter sur www.dodocho.top pour voir les coordonnées de votre hôte."
    )
    redirect_to host_housing_requests_path
  end


#     TwilioClient.messages.create(
#                   body: ".. accepted your request. His/her number is",
#                   # {current_user.name}
#                   # {current_user.phone_number}. It's your turn now!"
#                   from: '+12312448223',
#                   # to: "#{contact_request.seeker.phone_number}"
#                   to: "+33661634782")

  def decline
    @housing_request = HousingRequest.find(params[:id])
    @housing_request.status = "declined"
    @housing_request.save

    Client.messages.create(
      from: '+16108970968',
      to: @housing_request.seeker.phone_number,
      body: "Désolé, votre demande d'hébergement à été refusée."
    )
    redirect_to host_housing_requests_path
  end

    # TwilioClient.messages
    #             .create(
    #               body: " declined your request... :(",
    #               #{current_user.name}
    #               from: '+12312448223',
    #               # to: "#{contact_request.explorer.phone_number}"
    #               to: '+33661634782'
    #               )

  # def show
  #   @housing_request = HousingRequest.find(params[:id])
  # end

end

app/controllers/host/night_proposal_controller.rb
class Host::NightProposalsController < ApplicationController
def edit

end

def update

end
end

app/controllers/host/night_proposals_controller.rb
class Host::NightProposalsController < ApplicationController
  def edit
  end

  def update
    
    
  end
end

app/controllers/host/offered_equipments_controller.rb
class Host::OfferedEquipmentsController < ApplicationController
  def edit
    # @room = Roomd.find{params[:]}
    @user = current_user
  end

  def update
  end
end

app/controllers/host/rooms_controller.rb
class Host::RoomsController < ApplicationController
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.host = current_user
    if @room.save
      # renvoyer l'utilisateur vers le formulaire d'edit de la room pour ajouter les équipements
      redirect_to edit_host_offered_equipments_path
    else
      render 'new'
    end
  end

  private

  def room_params
    params.require(:room).permit(:id, :summary, :title, :body, :photos)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    # ! Ici nous avons accès à params[:address], qui nous est fourni par l'utilisateur sur l'écran précédent
    # search_infos/edit
    @rooms = Room.near(params[:address], 10)
    @address_coordinates = Geocoder.coordinates(params[:address])
  end

  def show
    @room = Room.find(params[:id])
    @rooms = Room.near(params[:address], 10)
    @address_coordinates = [params[:lat], params[:long]]
  end
end

app/views/host/rooms/_equipements.html.erb
<div class="services-container container mt-5">

  <div class="d-flex flex-column h-100">
    <h4>Les équipements dont la chambre dispose</h4>

    <%= simple_form_for @user, url: host_offered_equipments_path do |f| %>

      <div class="d-flex flex-column my-4 h-100">
        <div class="flex-grow-1">
          <div class="row">

            <% User::HOST_EQUIPMENTS.each do |equipment| %>
              <div class="my-2 for-check col-12">
                <input class="form-check-input is-valid check_boxes optional d-none" type="checkbox" value="<%= equipment %>" name="user[equipments][]" id="user_equipments_<%= equipment.downcase %>">
                <label for="user_equipments_<%= equipment.downcase %>" class="card-service card-service--<%= equipment_name_to_skill(equipment) %> flex-grow-1 shadow">
                  <div class="card-service-icon-wrapper card-service-icon-wrapper---<%= equipment_name_to_skill(equipment) %>"><%= image_tag("service-icons/#{equipment_name_to_skill(equipment)}.svg") %></div>

                    <div class="d-flex infos-services">
                      <div class="card-service-description-wrapper"><%= equipment %></div>
                      <i class="fas fa-check"></i>
                    </div>
                </label>
              </div>
            <% end %>
          </div>
        </div>
        <div>
          <%= f.submit "Suivant", class: "btn btn-gradient btn-block btn-lg my-5" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/host/rooms/_night.html.erb
<div class="moon-container global-container-wrapper container">
  <%= form_tag seeker_search_infos_path, class: "h-100", method: :patch do %>
    <div class="d-flex flex-column h-100">
      <div class="input-group mt-4">
        <span class="input-group-text py-6 mb-4" id="basic-addon1">
          <i class="fas fa-map-marker-alt"></i>
        </span>
        <%= text_field_tag "night_proposal[address]",
          params.dig(:search_infos, :address),
          placeholder: "Mon adresse",
          class: "form-control"
        %>

      </div>
      <div class="flex-grow-1">
        <p>Je propose ma chambre pour</p>
        <% 1.upto(HousingRequest::MAX_NIGHTS_COUNT) do |nights_count| %>
          <div class="mt-4">
          <br>

            <input class="d-none" type="radio" value="<%= nights_count %>" name="night_proposal[nights_count]" id="<%= "night_proposal_nights_count_#{nights_count}" %>">
            <label for="<%= "night_proposal_nights_count_#{nights_count}" %>" class="card-moon-night">
              <div class="card-moon-night-icon-wrapper"><%= image_tag('moon-stars.svg', width: 48) %></div>
              <p class="card-moon-night-description-wrapper pl-1 ">
                <%= "Une" if nights_count == 1 %>
                <%= "Deux " if nights_count == 2 %>
                <%= "Trois " if nights_count == 3 %> nuit<%= "s" if nights_count > 1 %>
              </p>
              <i class="fas fa-check"></i>
            </label>
          </div>
        <% end %>
      </div>
      <%= submit_tag "Valider",  class: "btn btn-gradient btn-block btn-lg my-3" %>
    </div>
  <% end %>
</div>

app/views/host/rooms/edit.html.erb
<div class="container mt-5">
  <h4>Les services que je peux offrir</h4>

  <%= simple_form_for @room, url: host_room_path(@room) do |f| %>
    <%#= f.input :services, as: :check_boxes, collection: ["Jardinage", "Courses", "Bricolage", "Cuisine", "Animaux"], include_hidden: false %>

    <div class="row">
      <div class="form-check col-12">
        <input type="hidden" value="0" name="room[has_books]">
        <input class="form-check-input is-valid check_boxes optional d-none" type="checkbox" checked="<%= "checked" if @room.has_books %>" name="room[has_books]" id="room_has_books">
        <label for="room_has_books" class="card-service shadow-sm">
            <div class="card-service-icon-wrapper card-service-icon-wrapper--gardening"><%= image_tag("service-icons/books.svg", width: 48) %></div>
            <div class="card-service-description-wrapper">Livres</div>
        </label>
      </div>
    </div>
        <div class="row">
      <div class="form-check col-12">
      <input type="hidden" value="0" name="room[has_tv]">
        <input class="form-check-input is-valid check_boxes optional d-none" type="checkbox" checked="<%= "checked" if @room.has_tv %>" name="room[has_tv]" id="room_has_tv">
        <label for="room_has_tv" class="card-service shadow-sm">
            <div class="card-service-icon-wrapper card-service-icon-wrapper--pet-walking"><%= image_tag("service-icons/television.svg", width: 48) %></div>
            <div class="card-service-description-wrapper">TV</div>
        </label>
      </div>
    </div>
        <div class="row">
      <div class="form-check col-12">
      <input type="hidden" value="0" name="room[has_internet]">
        <input class="form-check-input is-valid check_boxes optional d-none" type="checkbox" checked="<%= "checked" if @room.has_internet %>" name="room[has_internet]" id="room_has_internet">
        <label for="room_has_internet" class="card-service shadow-sm">
            <div class="card-service-icon-wrapper card-service-icon-wrapper--crafting"><%= image_tag("service-icons/internet.svg", width: 48) %></div>
            <div class="card-service-description-wrapper">Internet</div>
        </label>
      </div>
    </div>
        <div class="row">
      <div class="form-check col-12">
      <input type="hidden" value="0" name="room[has_personal_bathroom]">
        <input class="form-check-input is-valid check_boxes optional d-none" type="checkbox" checked="<%= "checked" if @room.has_personal_bathroom %>" name="room[has_personal_bathroom]" id="room_has_personal_bathroom">
        <label for="room_has_personal_bathroom" class="card-service shadow-sm">
            <div class="card-service-icon-wrapper card-service-icon-wrapper--shower"><%= image_tag("service-icons/shower.svg", width: 48) %></div>
            <div class="card-service-description-wrapper">Douche</div>
        </label>
      </div>
    </div>

    <%= f.submit "Suivant", class: "btn btn-gradient btn-block btn-lg mt-3" %>
  <% end %>


</div>

app/views/host/rooms/new.html.erb
<div class="host-profile container host-create d-flex flex-column py-3">
  <div class="host-1 flex-grow-1">
    <%= simple_form_for @room, url: host_rooms_path, method: :post do |f| %>
      <%# Desc %>
      <div class="page-1 h-100">
        <%= f.input :title, label: "Titre" %>
        <%= f.input :summary, as: :text, :input_html => { :rows => 5 }, label: "Description"%>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>

        <div class="ca">
          <div class ="cont-icone d-flex justify-content-center">
            <i style="font-size:2em; color:#FE5E41;" class="align-self-center fas fa-plus"></i>
          </div>
          <h1 class="pt-2">Ajouter une photo?</h1>
          <div class="d-flex">
            <h2 class="bu" style="font-size:1em;">Une photo de votre demeure est un signe de crédibilité</h2>
          </div>
        </div>

      </div>
      <%# Equipements %>
      <div class="my-4 page-2 h-100">
        <h4>Les équipements dont la chambre dispose</h4>
          <div class="d-flex flex-column h-100">
            <% User::HOST_EQUIPMENTS.each do |equipment| %>
              <div class="my-2 for-check col-12">
                <input class="form-check-input is-valid check_boxes optional d-none" type="checkbox" value="<%= equipment %>" name="user[equipments][]" id="user_equipments_<%= equipment.downcase %>">
                <label for="user_equipments_<%= equipment.downcase %>" class="card-service card-service--<%= equipment_name_to_skill(equipment) %> flex-grow-1 shadow">
                  <div class="card-service-icon-wrapper card-service-icon-wrapper---<%= equipment_name_to_skill(equipment) %>"><%= image_tag("service-icons/#{equipment_name_to_skill(equipment)}.svg") %></div>
                    <div class="d-flex infos-services">
                      <div class="card-service-description-wrapper"><%= equipment %></div>
                      <i class="fas fa-check"></i>
                    </div>
                  </div>
                </label>
              </div>
              <% end %>
          </div>

      <%# Nuits %>
      <div class="page-3 h-100">
        <%= render "host/rooms/night"%>
      </div>
    <% end %>
  </div>

    <div class="pb-3  container">
  </div>
</div>